<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Action" nsURI="http://action/1.0" nsPrefix="action">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftside" lowerBound="1"
        eType="#//LeftSide" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightside" lowerBound="1"
        eType="#//RightSide" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeftSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionRadio" eSuperTypes="#//RightSide">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newState" lowerBound="1"
        eType="#//RadioModes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        eType="#//Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        upperBound="2" eType="#//Operand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrecedingLogicOp" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="and"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="2"
        upperBound="-1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrecedingLogicOp" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="and"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logic" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="and"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparator" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//CompOp" defaultValueLiteral="greater"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//LeftSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="Math" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//MathOp" defaultValueLiteral="plus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes" eSuperTypes="#//Operand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//AttrTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Num" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strings" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOp">
    <eLiterals name="and"/>
    <eLiterals name="or" value="1"/>
    <eLiterals name="not" value="2"/>
    <eLiterals name="None" value="3"/>
    <eLiterals name="nand" value="4"/>
    <eLiterals name="nor" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompOp">
    <eLiterals name="greater"/>
    <eLiterals name="greater_equal" value="1"/>
    <eLiterals name="less" value="2"/>
    <eLiterals name="less_equal" value="3"/>
    <eLiterals name="equal" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MathOp">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="divided" value="2"/>
    <eLiterals name="multiplication" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AttrTypes">
    <eLiterals name="SecLevel"/>
    <eLiterals name="OpRole" value="1"/>
    <eLiterals name="CarrierFreq" value="2"/>
    <eLiterals name="SampleValues_ASC" value="3"/>
    <eLiterals name="SampleValues_DESC" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RadioModes">
    <eLiterals name="Mode_1"/>
    <eLiterals name="Mode_2" value="1"/>
    <eLiterals name="Mode_3" value="2"/>
    <eLiterals name="Mode_4" value="3"/>
  </eClassifiers>
</ecore:EPackage>
