<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Action" nsURI="http://action/1.0" nsPrefix="action">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EReference" name="leftside" lowerBound="1"
        eType="#//LeftSide" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rightside" lowerBound="1"
        eType="#//RightSide" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RightSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="LeftSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="ActionRadio" eSuperTypes="#//RightSide">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="newState" lowerBound="1"
        eType="#//RadioModes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operator" lowerBound="1"
        eType="#//Operator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" lowerBound="1"
        upperBound="2" eType="#//Operand" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrecedingLogicOp" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="None"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundExp" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" lowerBound="2"
        upperBound="-1" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="PrecedingLogicOp" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="None"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Logic" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//LogicOp" defaultValueLiteral="None"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comparator" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//CompOp" defaultValueLiteral="greater"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operator" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" eSuperTypes="#//LeftSide"/>
  <eClassifiers xsi:type="ecore:EClass" name="Math" eSuperTypes="#//Operator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Operation" lowerBound="1"
        eType="#//MathOp" defaultValueLiteral="plus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attributes" abstract="true" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operand" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="#//Operand"/>
  <eClassifiers xsi:type="ecore:EClass" name="Num" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Strings" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LogicOp">
    <eLiterals name="None"/>
    <eLiterals name="and" value="1"/>
    <eLiterals name="or" value="2"/>
    <eLiterals name="not" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompOp">
    <eLiterals name="greater"/>
    <eLiterals name="greater_equal" value="1"/>
    <eLiterals name="less" value="2"/>
    <eLiterals name="less_equal" value="3"/>
    <eLiterals name="equal" value="4"/>
    <eLiterals name="not_equal" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MathOp">
    <eLiterals name="plus"/>
    <eLiterals name="minus" value="1"/>
    <eLiterals name="divided" value="2"/>
    <eLiterals name="multiplication" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RadioModes">
    <eLiterals name="SILENT_MODE"/>
    <eLiterals name="ALERT_MODE" value="1"/>
    <eLiterals name="FULLDUPLEX_MODE" value="2"/>
    <eLiterals name="NORMAL_MODE" value="3"/>
    <eLiterals name="MAINTAIN_CURRENT_MODE" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuleSet">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rule" upperBound="-1" eType="#//Rule"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoolAttributes" eSuperTypes="#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="boolAttr" lowerBound="1"
        eType="#//BoolAttr" defaultValueLiteral="SNRValues_ASC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringAttributes" eSuperTypes="#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringAttr" lowerBound="1"
        eType="#//StringAttr" defaultValueLiteral="OpRole"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumAttributes" eSuperTypes="#//Attributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numAttr" lowerBound="1"
        eType="#//NumAttr" defaultValueLiteral="SecLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BoolAttr">
    <eLiterals name="SNRValues_ASC" value="3"/>
    <eLiterals name="SNRValues_DESC" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StringAttr">
    <eLiterals name="OpRole" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumAttr">
    <eLiterals name="SecLevel"/>
    <eLiterals name="CarrierFreq" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bool" eSuperTypes="#//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
